# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "Bad luck, bad drug or bad heart: Computer models to the rescue"
author: Henrik Finsberg
logo: "figures/logo.png"
copyright: "2022"
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  timeout: 3000

# Information about where the book exists on the web
repository:
  url: https://github.com/ComputationalPhysiology/uio-digital-scholarship-days # Online location of your book
  branch: main

html:
  use_issues_button: true
  use_repository_button: true

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - linkify

sphinx:
  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.napoleon'
  - 'sphinx.ext.viewcode'
