# Use github pages for docker image
FROM ghcr.io/fenics/dolfinx/dolfinx:nightly

RUN python3 -m pip install --no-cache-dir \
    gotran \
    jupyter \
    matplotlib \
    numpy \
    tqdm \
    simcardems \
    jupyter-book
